a=("Oneplus","Samsung","Redmi",99,1000)
print(type(a))
b=("Vivo")
print(type(b))
c=("Vivo",)
print(type(c))
print(a[::-1])
print("Before conversion of 'a' ",type(a))
a=list(a)
print("After conversion of 'a' ",type(a))
a.append("Oppo")
print(a)
a=tuple(a)
print(a)
print("After again conversion of 'a' ",type(a))
